"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

 type Stats = { totalTeamMembers: number; totalApplications: number; pendingApplications: number; acceptedApplications: number; recentApplications: { _id: string; fullName: string; registrationNumber: string; areaOfInterest: string; status?: string; createdAt: string }[] };

export default function AdminDashboardPage() {
  const [stats, setStats] = useState<Stats | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/admin/stats").then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.message); setStats(result); }).catch((loadError) => setError(loadError instanceof Error ? loadError.message : "Unable to load dashboard.")); }, []);
  if (error) return <main className="min-h-screen bg-[#08090b] p-8 text-red-200">{error}</main>;
  const cards = stats ? [["Total Team Members", stats.totalTeamMembers], ["Total Applications", stats.totalApplications], ["Pending Applications", stats.pendingApplications], ["Accepted Applications", stats.acceptedApplications]] : [];
  return <main className="min-h-screen bg-[#08090b] px-5 py-16 text-white sm:px-10 lg:px-16"><div className="mx-auto max-w-7xl"><p className="text-xs uppercase tracking-[0.3em] text-blue-300/60">Overview</p><h1 className="mt-4 text-4xl font-semibold tracking-tight">Dashboard</h1><p className="mt-3 text-sm text-white/40">A quiet view of the club behind the scenes.</p><div className="mt-10 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.length ? cards.map(([label, value]) => <div key={label} className="rounded-2xl border border-white/10 bg-[#0b0d10] p-6"><p className="text-xs uppercase tracking-[0.15em] text-white/35">{label}</p><p className="mt-5 text-4xl font-semibold">{value}</p></div>) : <div className="col-span-full py-20 text-center text-sm text-white/40">Loading dashboard...</div>}</div><div className="mt-8 grid gap-8 xl:grid-cols-[1fr_0.7fr]"><section className="rounded-2xl border border-white/10 bg-[#0b0d10] p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-medium">Recent Applications</h2><Link href="/admin/applications" className="text-sm text-blue-200">View all</Link></div><div className="mt-6 divide-y divide-white/[0.07]">{stats?.recentApplications.length ? stats.recentApplications.map((application) => <div key={application._id} className="flex flex-col gap-2 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-white/80">{application.fullName}</p><p className="mt-1 text-xs text-white/35">{application.registrationNumber} · {application.areaOfInterest}</p></div><span className="text-xs text-white/45">{application.status || "Pending"}</span></div>) : <p className="py-8 text-sm text-white/40">No applications yet.</p>}</div></section><section className="rounded-2xl border border-white/10 bg-[#0b0d10] p-6"><h2 className="text-xl font-medium">Quick Actions</h2><div className="mt-6 grid gap-3"><Link href="/admin/team" className="rounded-xl border border-white/10 px-4 py-3 text-sm text-white/70 transition hover:bg-white/10">Add Team Member</Link><Link href="/admin/applications" className="rounded-xl border border-white/10 px-4 py-3 text-sm text-white/70 transition hover:bg-white/10">View Applications</Link><Link href="/admin/team" className="rounded-xl border border-white/10 px-4 py-3 text-sm text-white/70 transition hover:bg-white/10">Manage Team</Link><Link href="/admin/applications" className="rounded-xl border border-white/10 px-4 py-3 text-sm text-white/70 transition hover:bg-white/10">Export Applications</Link></div></section></div></div></main>;
}
